themeName: rafhun
devUrl: cbp.dev
dbDump: db/

buildFolders:
  config: wwwroot/config/
  contentImg: wwwroot/images/content/
  customizing: wwwroot/customizing/
  editorConfig: wwwroot/core/Wysiwyg/
  fonts: fonts/
  icons: icons/
  img: images/
  styleguide: wwwroot/styleguide/
  theme: wwwroot/themes/

srcFolders:
  bower: src/bower_components/
  config: src/config/
  contentImg: src/images/content/
  css: src/css/
  customizing: src/customizing/
  fonts: src/fonts/
  icons: src/images/icons/
  iconsMin: src/images/icons/min/
  images: src/images/
  jade: src/jade/
  js: src/js/
  jsBuild: src/js/build/
  moleculesJs: src/js/molecules/
  scss: src/scss/
  secrets: src/secrets/
  themeImg: src/images/theme/
