# Directory to parse
source: ../src/scss/

# Directory to build the styleguide
destination: ../wwwroot/styleguide

# Hologram theme
documentation_assets: ../bower_components/Cortana
custom_markdown: ../bower_components/Cortana/CortanaMarkdownRenderer.rb

dependencies:


# To have a custom index page build with your README.md
index: README

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - ../src/css/style-prefixed.css

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - ../src/js/build/script.js

# String used to split the category name and create category wrapper
name_scope: ' - '
